<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginButton_STA</name>
   <tag></tag>
   <elementGuidId>0f9cd419-14de-47e4-9f5c-1e0d89f36245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/div[3]/div/div/div[1]/div/div/div[1]/div/div/div[2]/div/div/div/div/div[1]/div/form/fieldset/div[5]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
