<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_MediaChannel</name>
   <tag></tag>
   <elementGuidId>2cfde283-6991-482e-bbda-41d55b03f536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>ul[id^='select2-results-'][class='select2-results'][role='listbox']/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
