<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Template_Rendrer_dd</name>
   <tag></tag>
   <elementGuidId>b8ba2e5e-d2b9-4fe4-a329-8fbfdbe6aaf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div[13]/div/div/div[1]/div/div[2]/div/div[1]/div[2]/div[3]/div/div/a/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
