<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload_Package</name>
   <tag></tag>
   <elementGuidId>11308337-f956-42b8-b2e8-c7a1c477a092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/div[4]/div/div/div[14]/div/div/div[1]/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/input
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
