<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuOption_Design</name>
   <tag></tag>
   <elementGuidId>c1140371-30bb-4fb1-a4e6-cf1b11389668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;body&quot;]/main/div/div/div/div/div/div/div/div/div/table/tbody/tr[1]/td[8]/ul/li[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
