<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_AssetSearch</name>
   <tag></tag>
   <elementGuidId>add3397d-88ac-4dd6-b73d-3dfb7dc359f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type='text'][class='form-control']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
