<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Template_Variable_Delete_Button</name>
   <tag></tag>
   <elementGuidId>f40f181e-e4fd-4052-bd11-5c50589e0a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div/div/div/div/div/div/div/div/table/tbody/tr[1]/td[9]/ul/li[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
